name: Deploy .NET API to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: sa-east-1

      - name: Build Docker image
        run: |
          docker build -t inventory-api ./InventoryManagement

      - name: Tag Docker image for ECR
        run: |
          IMAGE_URI=${{ secrets.ECR_IMAGE_URI }}

          docker tag inventory-api $IMAGE_URI

      - name: Push Docker image to ECR
        run: |
          IMAGE_URI=${{ secrets.ECR_IMAGE_URI }}

          docker push $IMAGE_URI

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: sa-east-1
          cluster: inventory-cluster       # nome do cluster ECS
          service: inventory-api-service       # nome do serviço ECS
          task-definition: ecs-task-def.json  # arquivo de Task Definition
          image: ${{ secrets.ECR_IMAGE_URI }}

